services:
  jitsem_website:
    container_name: jitsem_website
    image: jitsem_website:latest
    restart: unless-stopped
    environment:
      RUST_LOG: "info"
    networks:
      - proxy
networks:
  proxy:
    external: true # created by the caddy compose, not here
